version: '3.9'

services:
  postgres:
    container_name: alxpostgresdb
    image: postgres
    ports:
      - '54321:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data' 
      - ./dumps/init.db.sh:/docker-entrypoint-initdb.d/init.db.sh
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8081:80"

volumes:
  postgres:
    name: "alxpostgresdb"
